import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// =====================
// TRANSLATIONS
// =====================
const translations: Record<Language, Record<string, string>> = {
  id: {
    // ── Sidebar / Nav ─────────────────────────────────────────────
    'nav.overview': 'Ringkasan',
    'nav.masterProducts': 'Master Produk',
    'nav.promo': 'Promo',
    'nav.transactions': 'Transaksi',
    'nav.branchInventory': 'Inventaris Cabang',
    'nav.userManagement': 'Manajemen Pengguna',
    'nav.broadcast': 'Siaran',
    'nav.aiInsights': 'Wawasan AI',
    'nav.aiTraining': 'Pelatihan AI',
    'nav.inventory': 'Inventaris',
    'nav.users': 'Pengguna',
    'nav.aiAnalysis': 'Wawasan AI',
    'nav.mainMenu': 'Menu Utama',
    'nav.signOut': 'Keluar',

    // ── Header ────────────────────────────────────────────────────
    'header.enterprise': 'Enterprise',
    'header.superAdmin': 'Super Admin',
    'header.branchAdmin': 'Admin Cabang',
    'header.statusOnline': 'Status: Online',

    // ── Language switcher ─────────────────────────────────────────
    'lang.label': 'Bahasa',
    'lang.id': 'Indonesia',
    'lang.en': 'English',

    // ── Page labels ───────────────────────────────────────────────
    'page.inventory': 'Inventaris',
    'page.promo': 'Promo',
    'page.users': 'Pengguna',
    'page.masterProducts': 'Master Produk',
    'page.dashboard': 'Dashboard',

    // ── Notifications ─────────────────────────────────────────────
    'notif.communicationCenter': 'Pusat Komunikasi',
    'notif.markAllRead': 'Tandai Semua Dibaca',
    'notif.markRead': 'Tandai Dibaca & Tutup',
    'notif.noNew': 'Tidak ada notifikasi baru',
    'notif.lowStock': '⚠️ Stok Rendah!',
    'notif.rejected': '❌ Pengajuan Ditolak',

    // ── Common / Shared ───────────────────────────────────────────
    'common.loading': 'Memuat...',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.search': 'Cari',
    'common.refresh': 'Refresh',
    'common.back': 'Kembali',
    'common.submit': 'Kirim',
    'common.confirm': 'Konfirmasi',
    'common.close': 'Tutup',
    'common.yes': 'Ya',
    'common.no': 'Tidak',
    'common.all': 'Semua',
    'common.active': 'Aktif',
    'common.inactive': 'Nonaktif',
    'common.status': 'Status',
    'common.name': 'Nama',
    'common.price': 'Harga',
    'common.stock': 'Stok',
    'common.category': 'Kategori',
    'common.action': 'Aksi',
    'common.noData': 'Tidak ada data',
    'common.retry': 'Coba Lagi',
    'common.export': 'Export',
    'common.create': 'Buat',
    'common.add': 'Tambah',
    'common.send': 'Kirim',
    'common.update': 'Perbarui',
    'common.view': 'Lihat',
    'common.allBranches': 'Semua Cabang',
    'common.branch': 'Cabang',
    'common.total': 'Total',
    'common.date': 'Tanggal',
    'common.period': 'Periode',
    'common.description': 'Deskripsi',
    'common.type': 'Tipe',
    'common.role': 'Role',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.username': 'Username',
    'common.clearFilters': 'Hapus Filter',
    'common.notFound': 'Tidak ditemukan',

    // ── Overview Page ─────────────────────────────────────────────
    'overview.subtitle': 'Analitik performa bisnis real-time',
    'overview.dataUpdated': 'Data diperbarui otomatis',
    'overview.healthScore': 'Skor kesehatan',
    'overview.exportReport': 'Export Laporan',
    'overview.generating': 'Memproses...',
    'overview.lowStockAlert': '⚠️ Perhatian: Sinyal Stok Kritis!',
    'overview.lowStockDesc': 'produk dengan kuantitas stok di bawah 10 pcs. Segera lakukan penambahan stok!',
    'overview.manageStock': 'Kelola Stok',
    'overview.totalRevenue': 'Total Pendapatan',
    'overview.totalProducts': 'Total Produk',
    'overview.totalBranches': 'Total Cabang',
    'overview.activePromos': 'Promo Aktif',
    'overview.stockStatus': 'Status Stok',
    'overview.healthy': 'Sehat',
    'overview.lowStock': 'Stok Rendah',
    'overview.normal': 'Normal',
    'overview.critical': 'Kritis',
    'overview.vsLastWeek': 'vs minggu lalu',
    'overview.vsLastMonth': 'vs bulan lalu',
    'overview.vsLastYear': 'vs tahun lalu',
    'overview.vsLastCycle': 'vs periode lalu',
    'overview.syncingData': 'Menyinkronkan Data Enterprise...',
    'overview.systemDesync': 'Sistem Desync',
    'overview.retryConnection': 'Coba Lagi Koneksi',
    'overview.noDataFound': 'Tidak ada data operasional untuk pilihan ini.',
    'overview.enterpriseSalesVelocity': 'Kecepatan Penjualan Enterprise',
    'overview.velocityPerformance': 'Kecepatan Performa',
    'overview.consolidatedDesc': 'Distribusi transaksi terkonsolidasi di seluruh jaringan.',
    'overview.realtimeDesc': 'Analitik real-time untuk',
    'overview.operationalGroup': 'kelompok operasional.',
    'overview.showingData': 'Menampilkan data',
    'overview.topProductsSales': 'Penjualan Produk Teratas',
    'overview.topProductsDesc': 'Produk dengan pendapatan tertinggi berdasarkan periode',
    'overview.categoryContribution': 'Kontribusi Kategori',
    'overview.categoryDesc': 'Alokasi proporsional kategori produk berdasarkan keuntungan kotor',
    'overview.productSalesTable': 'Tabel Analitik Penjualan Produk',
    'overview.productSalesTableDesc': 'Detail jumlah penjualan produk individual dan kontribusi pendapatan',
    'overview.searchProduct': 'Cari produk, SKU, kategori...',
    'overview.allCategories': 'Semua Kategori',
    'overview.productInfo': 'Informasi Produk',
    'overview.basePrice': 'Harga Dasar',
    'overview.qtySold': 'Qty Terjual',
    'overview.totalRevenue2': 'Total Pendapatan',
    'overview.noProductMatch': 'Tidak ada produk yang cocok dengan pencarian Anda.',
    'overview.noSalesData': 'Belum ada data penjualan pada periode ini.',
    'overview.noCategoryData': 'Belum ada data kategori.',
    'overview.clickViewDetails': 'Klik untuk lihat detail',
    'overview.growthInfo': 'Pertumbuhan dibandingkan periode sebelumnya berdasarkan filter aktif',

    // ── Inventory Page ────────────────────────────────────────────
    'inventory.subtitle': 'Kelola stok dan produk cabang Anda',
    'inventory.registered': 'produk terdaftar',
    'inventory.lastUpdated': 'Terakhir diperbarui hari ini',
    'inventory.addStock': 'Tambah Stok',
    'inventory.requestNewProduct': 'Ajukan Produk Baru',
    'inventory.totalAssets': 'Total Aset',
    'inventory.calculatedValue': 'Nilai saat ini terhitung',
    'inventory.lowStockAlerts': 'Peringatan Stok Rendah',
    'inventory.requiresAttention': 'Perlu perhatian',
    'inventory.skuCount': 'Jumlah SKU',
    'inventory.totalUniqueProducts': 'Total produk unik',
    'inventory.searchCatalog': 'Cari katalog...',
    'inventory.product': 'Produk',
    'inventory.sku': 'SKU',
    'inventory.aiStatus': 'Status AI',
    'inventory.noAiLabel': 'Belum Ada',
    'inventory.modifyStock': 'Ubah Detail Stok',
    'inventory.productName': 'Nama Produk',
    'inventory.stockCount': 'Jumlah Stok',
    'inventory.unitPrice': 'Harga Satuan',
    'inventory.applyChanges': 'Terapkan Perubahan',
    'inventory.deleteProduct': 'Hapus Produk?',
    'inventory.deleteStock': 'Hapus Stok?',
    'inventory.deleteProductDesc': 'Kamu akan menghapus "{name}" secara permanen dari katalog master dan sistem penyimpanan.',
    'inventory.deleteStockDesc': 'Apakah kamu yakin ingin menghapus "{name}" dari stok cabang ini?',
    'inventory.deleting': 'Menghapus...',
    'inventory.confirmDelete': 'Ya, Hapus',
    'inventory.items': 'Item',
    'inventory.deleteSuccess': 'berhasil dihapus',
    'inventory.deleteFailed': 'Gagal menghapus',

    // ── Add Inventory Page ────────────────────────────────────────
    'addInventory.title': 'Tambah Produk Cabang',
    'addInventory.subtitle': 'Ambil produk dari master catalog atau ajukan baru ke Super Admin',
    'addInventory.backToStock': 'Kembali Ke Stok',
    'addInventory.searchProduct': 'Cari nama produk, SKU, kategori...',
    'addInventory.syncingCatalog': 'Sinkronisasi Katalog Master...',
    'addInventory.noProductAvailable': 'Tidak ada produk tersedia',
    'addInventory.noProductDesc': 'Seluruh produk katalog master telah dimasukkan ke toko Anda, atau tidak ada yang cocok dengan kata kunci.',
    'addInventory.branchStockSettings': 'Pengaturan Stok Cabang',
    'addInventory.branchStockDesc': 'Input stok awal dan harga khusus toko Anda',
    'addInventory.selectedProduct': 'Produk Terpilih',
    'addInventory.initialStock': 'Stok Awal',
    'addInventory.branchCustomPrice': 'Harga Khusus Cabang (Rp)',
    'addInventory.defaultMasterPrice': 'Bawaan master jika kosong',
    'addInventory.masterDefault': 'Bawaan Master',
    'addInventory.connecting': 'Menghubungkan...',
    'addInventory.addToStore': 'Tambahkan ke Toko',
    'addInventory.selectMasterFirst': 'Pilih produk master dahulu',
    'addInventory.selectMasterDesc': 'Silakan klik salah satu produk di daftar sebelah kiri untuk memproses stok cabang.',
    'addInventory.takePhoto': 'Ambil Foto',
    'addInventory.centerProduct': 'Posisikan produk tepat di tengah kamera',
    'addInventory.tapToFocus': 'Ketuk untuk fokus',
    'addInventory.successLinked': 'Berhasil menambahkan ke toko Anda!',
    'addInventory.successRequest': '🚀 Pengajuan produk baru berhasil dikirim ke Super Admin!',
    'addInventory.errorPhoto': '⚠️ Silakan lengkapi foto dari 4 sudut produk terlebih dahulu!',

    // ── Request Product Page ──────────────────────────────────────
    'request.title': 'Ajukan Produk Baru',
    'request.subtitle': 'Kirim pengajuan ke Super Admin untuk persetujuan',
    'request.back': 'Kembali',
    'request.needApproval': 'Perlu Persetujuan Super Admin',
    'request.approvalDesc': 'Produk yang Anda ajukan akan direview terlebih dahulu. Setelah disetujui, produk otomatis masuk ke katalog master dan bisa dideteksi oleh scanner AI.',
    'request.productInfo': 'Informasi Produk',
    'request.productInfoDesc': 'Detail produk yang diajukan',
    'request.productName': 'Nama Produk *',
    'request.namePlaceholder': 'Misal: Kopi Susu Aren',
    'request.proposedPrice': 'Harga yang Diajukan (Rp) *',
    'request.category': 'Kategori',
    'request.categoryPlaceholder': 'Misal: Minuman, Snack...',
    'request.reason': 'Alasan Pengajuan *',
    'request.reasonPlaceholder': 'Misal: Produk baru yang banyak diminati pelanggan',
    'request.photos4Angles': 'Foto 4 Sudut + Video (Wajib)',
    'request.photosDesc': 'Untuk identifikasi AI Vision',
    'request.photos': 'Foto',
    'request.sending': 'Mengirim Pengajuan...',
    'request.sendToAdmin': 'Kirim Pengajuan ke Super Admin',
    'request.front': 'Depan',
    'request.backAngle': 'Belakang',
    'request.left': 'Kiri',
    'request.right': 'Kanan',
    'request.front-left': 'Depan Kiri',
    'request.front-right': 'Depan Kanan',
    'request.back-left': 'Belakang Kiri',
    'request.back-right': 'Belakang Kanan',
    'request.photoTaken': 'Foto berhasil diambil!',
    'request.successSent': '🚀 Pengajuan berhasil dikirim ke Super Admin!',

    // ── Promo Page ────────────────────────────────────────────────
    'promo.subtitle': 'Kelola kampanye promosi dan distribusi voucher',
    'promo.subtitleDesc': 'Buat, edit, dan pantau promo aktif',
    'promo.launchCampaign': 'Buat Kampanye',
    'promo.totalCampaign': 'Total Kampanye',
    'promo.activeArchive': 'aktif & arsip',
    'promo.totalRedemption': 'Total Redemption',
    'promo.campaignReach': 'Jangkauan Kampanye',
    'promo.effectiveness': 'efektivitas',
    'promo.noCampaign': 'Belum ada kampanye',
    'promo.noCampaignDesc': 'Klik "Buat Kampanye" untuk mulai',
    'promo.createCampaign': 'Buat Kampanye',
    'promo.deleteCampaign': 'Hapus Kampanye?',
    'promo.deleteDesc': 'Kampanye ini akan dihapus permanen dan tidak bisa dikembalikan.',
    'promo.deleting': 'Menghapus...',
    'promo.confirmDelete': 'Ya, Hapus',
    'promo.discountValue': 'Nilai Diskon',
    'promo.voucherCode': 'Kode Voucher',
    'promo.quotaUsed': 'Kuota Terpakai',
    'promo.validAt': 'Berlaku Di',
    'promo.allBranches': 'Semua Cabang',
    'promo.specificBranch': 'Cabang Tertentu',
    'promo.period': 'Periode',
    'promo.usageLimit': 'Batas Penggunaan',
    'promo.usageLimitDesc': 'Maks. {n}x transaksi per pengguna',
    'promo.exclusive': 'Eksklusif',
    'promo.insights': 'Insights',
    'promo.globalAnalytics': 'Analitik Global',
    'promo.powerTip': 'Tips Ampuh',
    'promo.powerTipDesc': 'Voucher eksklusif untuk member loyal bisa meningkatkan retensi hingga 35%. Gunakan fitur "User Tertentu" untuk targeting yang lebih presisi.',
    'promo.deleteSuccess': 'Kampanye berhasil dihapus',
    'promo.deleteFailed': 'Gagal menghapus kampanye',

    // ── Users Page ────────────────────────────────────────────────
    'users.subtitle': 'Kelola akses, role, dan data pengguna sistem',
    'users.registered': 'pengguna terdaftar',
    'users.addUser': 'Tambah User',
    'users.superAdmin': 'Super Admin',
    'users.branchAdmin': 'Branch Admin',
    'users.member': 'Member',
    'users.cashier': 'Kasir',
    'users.activeUsers': 'Pengguna Aktif',
    'users.totalMember': 'Total Member',
    'users.activeMember': 'Member Aktif',
    'users.totalMemberPoints': 'Total Poin Member',
    'users.serverStatus': 'Status Server',
    'users.searchPlaceholder': 'Cari nama atau email...',
    'users.allRoles': 'Semua Role',
    'users.tableUser': 'Pengguna',
    'users.tableRole': 'Role',
    'users.tableBranch': 'Cabang',
    'users.tableStatus': 'Status',
    'users.tablePoints': 'Poin',
    'users.tableAction': 'Aksi',
    'users.noMatch': 'Tidak ada identitas yang cocok dengan filter Anda.',
    'users.clearAllFilters': 'Hapus semua filter',
    'users.editIdentity': 'Edit Identitas',
    'users.editDesc': 'Perbarui detail profil dan hak akses.',
    'users.fullName': 'Nama Lengkap',
    'users.enterFullName': 'Masukkan nama lengkap',
    'users.emailAddress': 'Alamat Email',
    'users.locationAssignment': 'Penugasan Lokasi',
    'users.selectLocation': 'Pilih Lokasi',
    'users.userRole': 'Role Pengguna',
    'users.roleImmutable': '* Tipe role tidak bisa diubah. Cabut akses untuk mengubah role.',
    'users.discardChanges': 'Batalkan Perubahan',
    'users.updateIdentity': 'Perbarui Identitas',
    'users.revokeAccess': 'Cabut Akses',
    'users.revokeDesc': 'Apakah Anda yakin ingin mencabut akses untuk {name}? Ini akan menghapus akun dan akses terminal mereka secara permanen.',
    'users.keepUser': 'Tidak, Pertahankan',
    'users.revokeNow': 'Cabut Sekarang',
    'users.sendVoucher': 'Kirim Voucher',
    'users.sendVoucherDesc': 'Berikan kode promo khusus langsung ke {name}.',
    'users.voucherCode': 'Kode Voucher',
    'users.discountType': 'Tipe Diskon',
    'users.discountValue': 'Nilai Diskon',
    'users.minPurchase': 'Min. Pembelian (Opsional)',
    'users.syncingIdentities': 'Menyinkronkan Identitas...',
    'users.identityCreated': 'Identitas berhasil dibuat',
    'users.identityUpdated': 'Identitas berhasil diperbarui',
    'users.identityRevoked': 'Akses dicabut untuk {name}',
    'users.voucherSent': 'Voucher dikirim ke {name}',

    // ── Create User Page ──────────────────────────────────────────
    'createUser.title': 'Buat Pengguna Baru',
    'createUser.subtitle': 'Tambahkan anggota tim baru ke sistem',
    'createUser.back': 'Kembali ke Pengguna',
    'createUser.fullName': 'Nama Lengkap',
    'createUser.email': 'Email',
    'createUser.role': 'Role',
    'createUser.password': 'Password',
    'createUser.branch': 'Cabang',
    'createUser.creating': 'Membuat...',
    'createUser.create': 'Buat Pengguna',

    // ── Broadcast Page ────────────────────────────────────────────
    'broadcast.subtitle': 'Kirim pengumuman ke seluruh cabang dan pengguna',
    'broadcast.subtitleDesc': 'Pusat komunikasi dan notifikasi',
    'broadcast.composeMessage': 'Buat Pesan',
    'broadcast.targetAudience': 'Target Audiens',
    'broadcast.selectAudience': 'Pilih Audiens',
    'broadcast.allBranches': 'Semua Cabang',
    'broadcast.specificBranch': 'Cabang Tertentu',
    'broadcast.allMembers': 'Semua Member',
    'broadcast.selectBranch': 'Pilih Cabang',
    'broadcast.targetBranch': 'Target Cabang',
    'broadcast.subjectHeader': 'Subjek / Judul',
    'broadcast.subjectPlaceholder': 'Misal: Pengumuman Pemeliharaan Sistem',
    'broadcast.messageBody': 'Isi Pesan',
    'broadcast.messagePlaceholder': 'Jelaskan pembaruan secara detail...',
    'broadcast.warningAllMembers': 'Pesan ini akan dikirim ke semua Member yang terdaftar (Push Notifications diaktifkan).',
    'broadcast.warningSpecificBranch': 'Pesan ini akan dikirim ke admin di {branch}.',
    'broadcast.warningAllBranches': 'Pesan ini akan langsung dikirim sebagai notifikasi push ke semua manajer cabang yang aktif.',
    'broadcast.sending': 'Mengirim...',
    'broadcast.dispatch': 'Kirim Broadcast',
    'broadcast.recipients': 'Penerima',
    'broadcast.target': 'Target',
    'broadcast.allMembersLabel': 'Semua Member',
    'broadcast.branchAdminLabel': 'Admin Cabang',
    'broadcast.allBranchAdmins': 'Semua Admin Cabang',
    'broadcast.targetScope': 'Cakupan Target',
    'broadcast.global': 'Global',
    'broadcast.local': 'Lokal',
    'broadcast.network': 'Jaringan',
    'broadcast.integrityStatus': 'Status Integritas',
    'broadcast.active': 'Aktif',
    'broadcast.recentHistory': 'Riwayat Terbaru',
    'broadcast.noHistory': 'Tidak ada riwayat broadcast.',
    'broadcast.loadingHub': 'Memuat Pusat Komunikasi...',
    'broadcast.successSent': 'Broadcast berhasil dikirim!',
    'broadcast.fillAllFields': 'Mohon isi semua kolom',

    // ── Transactions Page ─────────────────────────────────────────
    'transactions.subtitle': 'Riwayat transaksi dan pembayaran',
    'transactions.subtitleDesc': 'Pantau seluruh aktivitas penjualan',
    'transactions.totalTransactions': 'Total Transaksi',
    'transactions.totalRevenue': 'Total Pendapatan',
    'transactions.avgOrder': 'Rata-rata Order',
    'transactions.completed': 'Selesai',
    'transactions.searchInvoice': 'Cari nomor invoice...',
    'transactions.allBranches': 'Semua Cabang',
    'transactions.searchBranch': 'Cari cabang...',
    'transactions.branchNotFound': 'Tidak ditemukan.',
    'transactions.newest': 'Terbaru',
    'transactions.oldest': 'Terlama',
    'transactions.highest': 'Terbesar',
    'transactions.lowest': 'Terkecil',
    'transactions.list': 'Daftar Transaksi',
    'transactions.found': 'transaksi ditemukan',
    'transactions.noTransactions': 'Tidak ada transaksi',
    'transactions.invoice': 'Invoice',
    'transactions.date': 'Tanggal',
    'transactions.branch': 'Cabang',
    'transactions.total': 'Total',
    'transactions.status': 'Status',
    'transactions.customer': 'Pelanggan',
    'transactions.items': 'Item',
    'transactions.detail': 'Detail Transaksi',
    'transactions.page': 'Halaman',
    'transactions.of': 'dari',

    // ── Monitor Page ──────────────────────────────────────────────
    'monitor.subtitle': 'Pantau stok inventaris di seluruh cabang',
    'monitor.subtitleDesc': 'Update real-time dari semua lokasi',
    'monitor.searchBranch': 'Cari cabang...',
    'monitor.totalBranches': 'Total Cabang',
    'monitor.activeLocations': 'lokasi aktif',
    'monitor.lowStockItems': 'Item Stok Rendah',
    'monitor.acrossNetwork': 'di seluruh jaringan',
    'monitor.criticalAlerts': 'Peringatan Kritis',
    'monitor.needRestock': 'perlu restock',
    'monitor.items': 'item',
    'monitor.noBranch': 'Tidak ada cabang ditemukan',
    'monitor.lowStock': 'Stok Rendah',
    'monitor.healthy': 'Sehat',
    'monitor.outOfStock': 'Habis',
    'monitor.total': 'Total',
    'monitor.product': 'Produk',
    'monitor.sku': 'SKU',
    'monitor.stock': 'Stok',
    'monitor.lastUpdated': 'Update Terakhir',

    // ── AI Insights / Analysis ────────────────────────────────────
    'ai.title': 'Wawasan AI',
    'ai.subtitle': 'Analisis cerdas berbasis kecerdasan buatan',
    'ai.analyzing': 'Menganalisis...',
    'ai.generateInsights': 'Buat Wawasan',
    'ai.noInsights': 'Belum ada wawasan',
    'ai.noInsightsDesc': 'Klik tombol di atas untuk memulai analisis AI',
    'ai.recommendations': 'Rekomendasi',
    'ai.trends': 'Tren',
    'ai.alerts': 'Peringatan',

    // ── Login Page ────────────────────────────────────────────────
    'login.welcomeBack': 'Selamat Datang Kembali',
    'login.subtitle': 'Masukkan kredensial Anda untuk mengelola unit bisnis yang ditugaskan.',
    'login.username': 'Username',
    'login.usernamePlaceholder': 'Masukkan username Anda',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Masukkan password Anda',
    'login.signIn': 'Masuk ke Dashboard',
    'login.signingIn': 'Sedang Masuk...',
    'login.tagline': 'Kecerdasan Bisnis Terpadu.',
    'login.taglineDesc': 'Kendalikan penuh operasi enterprise Anda dengan pemantauan data terpusat dan sinkronisasi inventaris real-time.',

    // ── Branch Selector / Context ─────────────────────────────────
    'branch.consolidated': 'TERKONSOLIDASI',
    'branch.yourBranch': 'CABANG ANDA',
    'branch.selectUnit': 'Pilih Unit Operasional',

    // ── Export Modal ──────────────────────────────────────────────
    'export.title': 'Export Laporan - {branch}',
    'export.desc': 'Siapkan laporan PDF terkonsolidasi untuk tampilan saat ini. Ini akan mencakup kecepatan penjualan, metrik pendapatan, dan status kesehatan cabang untuk tinjauan operasional tingkat tinggi.',
    'export.confirm': 'Konfirmasi & Cetak',
    'export.processing': 'Memproses...',

    // ── Adjust Stock Modal ────────────────────────────────────────
    'adjustStock.title': 'Sesuaikan Stok',
    'adjustStock.subtitle': 'Memperbarui inventaris untuk {name}. Stok saat ini: {stock}.',
    'adjustStock.movementType': 'Tipe Pergerakan',
    'adjustStock.selectType': 'Pilih tipe',
    'adjustStock.restock': 'Stok Masuk (+)',
    'adjustStock.sale': 'Penjualan Manual (-)',
    'adjustStock.damage': 'Kerusakan/Kehilangan (-)',
    'adjustStock.adjustment': 'Penyesuaian Absolut (=)',
    'adjustStock.quantity': 'Jumlah',
    'adjustStock.reason': 'Alasan / Catatan (Opsional)',
    'adjustStock.reasonPlaceholder': 'Misal: Dikirim oleh supplier ABC',
    'adjustStock.confirmUpdate': 'Konfirmasi Pembaruan',
  },

  en: {
    // ── Sidebar / Nav ─────────────────────────────────────────────
    'nav.overview': 'Overview',
    'nav.masterProducts': 'Master Products',
    'nav.promo': 'Promo',
    'nav.transactions': 'Transactions',
    'nav.branchInventory': 'Branch Inventory',
    'nav.userManagement': 'User Management',
    'nav.broadcast': 'Broadcast',
    'nav.aiInsights': 'AI Insights',
    'nav.aiTraining': 'AI Training',
    'nav.inventory': 'Inventory',
    'nav.users': 'Users',
    'nav.aiAnalysis': 'AI Insights',
    'nav.mainMenu': 'Main Menu',
    'nav.signOut': 'Sign Out',

    // ── Header ────────────────────────────────────────────────────
    'header.enterprise': 'Enterprise',
    'header.superAdmin': 'Super Admin',
    'header.branchAdmin': 'Branch Admin',
    'header.statusOnline': 'Status: Online',

    // ── Language switcher ─────────────────────────────────────────
    'lang.label': 'Language',
    'lang.id': 'Indonesia',
    'lang.en': 'English',

    // ── Page labels ───────────────────────────────────────────────
    'page.inventory': 'Inventory',
    'page.promo': 'Promo',
    'page.users': 'Users',
    'page.masterProducts': 'Master Products',
    'page.dashboard': 'Dashboard',

    // ── Notifications ─────────────────────────────────────────────
    'notif.communicationCenter': 'Communication Center',
    'notif.markAllRead': 'Mark All as Read',
    'notif.markRead': 'Mark as Read & Close',
    'notif.noNew': 'No new notifications',
    'notif.lowStock': '⚠️ Low Stock!',
    'notif.rejected': '❌ Request Rejected',

    // ── Common / Shared ───────────────────────────────────────────
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.status': 'Status',
    'common.name': 'Name',
    'common.price': 'Price',
    'common.stock': 'Stock',
    'common.category': 'Category',
    'common.action': 'Action',
    'common.noData': 'No data available',
    'common.retry': 'Retry',
    'common.export': 'Export',
    'common.create': 'Create',
    'common.add': 'Add',
    'common.send': 'Send',
    'common.update': 'Update',
    'common.view': 'View',
    'common.allBranches': 'All Branches',
    'common.branch': 'Branch',
    'common.total': 'Total',
    'common.date': 'Date',
    'common.period': 'Period',
    'common.description': 'Description',
    'common.type': 'Type',
    'common.role': 'Role',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.username': 'Username',
    'common.clearFilters': 'Clear Filters',
    'common.notFound': 'Not found',

    // ── Overview Page ─────────────────────────────────────────────
    'overview.subtitle': 'Real-time business performance analytics',
    'overview.dataUpdated': 'Data auto-updated',
    'overview.healthScore': 'Health score',
    'overview.exportReport': 'Export Report',
    'overview.generating': 'Generating...',
    'overview.lowStockAlert': '⚠️ Warning: Critical Stock Signal!',
    'overview.lowStockDesc': 'products with stock quantity below 10 pcs. Please replenish stock immediately!',
    'overview.manageStock': 'Manage Stock',
    'overview.totalRevenue': 'Total Revenue',
    'overview.totalProducts': 'Total Products',
    'overview.totalBranches': 'Total Branches',
    'overview.activePromos': 'Active Promos',
    'overview.stockStatus': 'Stock Status',
    'overview.healthy': 'Healthy',
    'overview.lowStock': 'Low Stock',
    'overview.normal': 'Normal',
    'overview.critical': 'Critical',
    'overview.vsLastWeek': 'vs last week',
    'overview.vsLastMonth': 'vs last month',
    'overview.vsLastYear': 'vs last year',
    'overview.vsLastCycle': 'vs last cycle',
    'overview.syncingData': 'Synchronizing Enterprise Data...',
    'overview.systemDesync': 'System Desync',
    'overview.retryConnection': 'Retry Connection',
    'overview.noDataFound': 'No operational data found for this selection.',
    'overview.enterpriseSalesVelocity': 'Enterprise Sales Velocity',
    'overview.velocityPerformance': 'Velocity Performance',
    'overview.consolidatedDesc': 'Consolidated transaction distribution across network.',
    'overview.realtimeDesc': 'Real-time analytics for',
    'overview.operationalGroup': 'operational group.',
    'overview.showingData': 'Showing data',
    'overview.topProductsSales': 'Top Products Sales',
    'overview.topProductsDesc': 'Highest generating items based on timeframe sales',
    'overview.categoryContribution': 'Category Contribution',
    'overview.categoryDesc': 'Proportional allocation of product categories by gross profit',
    'overview.productSalesTable': 'Product Sales Analytics Table',
    'overview.productSalesTableDesc': 'Detail of individual product sales quantity and revenue contribution',
    'overview.searchProduct': 'Search product, SKU, category...',
    'overview.allCategories': 'All Categories',
    'overview.productInfo': 'Product Information',
    'overview.basePrice': 'Base Price',
    'overview.qtySold': 'Qty Sold',
    'overview.totalRevenue2': 'Total Revenue',
    'overview.noProductMatch': 'No products match your search.',
    'overview.noSalesData': 'No sales data for this period.',
    'overview.noCategoryData': 'No category data.',
    'overview.clickViewDetails': 'Click to view details',
    'overview.growthInfo': 'Growth compared to previous period based on your active filter',

    // ── Inventory Page ────────────────────────────────────────────
    'inventory.subtitle': 'Manage your branch stock and products',
    'inventory.registered': 'products registered',
    'inventory.lastUpdated': 'Last updated today',
    'inventory.addStock': 'Add Stock',
    'inventory.requestNewProduct': 'Request New Product',
    'inventory.totalAssets': 'Total Assets',
    'inventory.calculatedValue': 'Calculated current value',
    'inventory.lowStockAlerts': 'Low Stock Alerts',
    'inventory.requiresAttention': 'Requires attention',
    'inventory.skuCount': 'SKU Count',
    'inventory.totalUniqueProducts': 'Total unique products',
    'inventory.searchCatalog': 'Search catalog...',
    'inventory.product': 'Product',
    'inventory.sku': 'SKU',
    'inventory.aiStatus': 'AI Status',
    'inventory.noAiLabel': 'Not yet',
    'inventory.modifyStock': 'Modify Stock Details',
    'inventory.productName': 'Product Name',
    'inventory.stockCount': 'Stock Count',
    'inventory.unitPrice': 'Unit Price',
    'inventory.applyChanges': 'Apply Changes',
    'inventory.deleteProduct': 'Delete Product?',
    'inventory.deleteStock': 'Delete Stock?',
    'inventory.deleteProductDesc': 'You will permanently delete "{name}" from the master catalog and storage system.',
    'inventory.deleteStockDesc': 'Are you sure you want to delete "{name}" from this branch stock?',
    'inventory.deleting': 'Deleting...',
    'inventory.confirmDelete': 'Yes, Delete',
    'inventory.items': 'Items',
    'inventory.deleteSuccess': 'successfully deleted',
    'inventory.deleteFailed': 'Failed to delete',

    // ── Add Inventory Page ────────────────────────────────────────
    'addInventory.title': 'Add Branch Product',
    'addInventory.subtitle': 'Pull from master catalog or request a new product from Super Admin',
    'addInventory.backToStock': 'Back to Stock',
    'addInventory.searchProduct': 'Search product name, SKU, category...',
    'addInventory.syncingCatalog': 'Syncing Master Catalog...',
    'addInventory.noProductAvailable': 'No products available',
    'addInventory.noProductDesc': 'All master catalog products have been added to your store, or none match the keyword.',
    'addInventory.branchStockSettings': 'Branch Stock Settings',
    'addInventory.branchStockDesc': 'Input initial stock and custom price for your store',
    'addInventory.selectedProduct': 'Selected Product',
    'addInventory.initialStock': 'Initial Stock',
    'addInventory.branchCustomPrice': 'Branch Custom Price (Rp)',
    'addInventory.defaultMasterPrice': 'Defaults to master if empty',
    'addInventory.masterDefault': 'Master Default',
    'addInventory.connecting': 'Linking...',
    'addInventory.addToStore': 'Add to Store',
    'addInventory.selectMasterFirst': 'Select a master product first',
    'addInventory.selectMasterDesc': 'Click one of the products on the left list to process branch stock.',
    'addInventory.takePhoto': 'Take Photo',
    'addInventory.centerProduct': 'Position the product in the center of the camera',
    'addInventory.tapToFocus': 'Tap to focus',
    'addInventory.successLinked': 'Successfully added to your store!',
    'addInventory.successRequest': '🚀 New product request successfully sent to Super Admin!',
    'addInventory.errorPhoto': '⚠️ Please complete photos from all 4 angles first!',

    // ── Request Product Page ──────────────────────────────────────
    'request.title': 'Request New Product',
    'request.subtitle': 'Submit a request to Super Admin for approval',
    'request.back': 'Back',
    'request.needApproval': 'Requires Super Admin Approval',
    'request.approvalDesc': 'Your submitted product will be reviewed first. Once approved, the product will automatically enter the master catalog and can be detected by the AI scanner.',
    'request.productInfo': 'Product Information',
    'request.productInfoDesc': 'Details of the requested product',
    'request.productName': 'Product Name *',
    'request.namePlaceholder': 'e.g. Brown Sugar Latte',
    'request.proposedPrice': 'Proposed Price (Rp) *',
    'request.category': 'Category',
    'request.categoryPlaceholder': 'e.g. Beverage, Snack...',
    'request.reason': 'Reason for Request *',
    'request.reasonPlaceholder': 'e.g. New product with high customer demand',
    'request.photos4Angles': '4-Angle Photos + Video (Required)',
    'request.photosDesc': 'For AI Vision identification',
    'request.photos': 'Photos',
    'request.sending': 'Submitting...',
    'request.sendToAdmin': 'Send Request to Super Admin',
    'request.front': 'Front',
    'request.backAngle': 'Back',
    'request.left': 'Left',
    'request.right': 'Right',
    'request.front-left': 'Front-Left',
    'request.front-right': 'Front-Right',
    'request.back-left': 'Back-Left',
    'request.back-right': 'Back-Right',
    'request.photoTaken': 'Photo captured successfully!',
    'request.successSent': '🚀 Request successfully sent to Super Admin!',

    // ── Promo Page ────────────────────────────────────────────────
    'promo.subtitle': 'Manage promotional campaigns and voucher distribution',
    'promo.subtitleDesc': 'Create, edit, and monitor active promos',
    'promo.launchCampaign': 'Launch Campaign',
    'promo.totalCampaign': 'Total Campaigns',
    'promo.activeArchive': 'active & archive',
    'promo.totalRedemption': 'Total Redemption',
    'promo.campaignReach': 'Campaign Reach',
    'promo.effectiveness': 'effectiveness',
    'promo.noCampaign': 'No campaigns yet',
    'promo.noCampaignDesc': 'Click "Launch Campaign" to start',
    'promo.createCampaign': 'Create Campaign',
    'promo.deleteCampaign': 'Delete Campaign?',
    'promo.deleteDesc': 'This campaign will be permanently deleted and cannot be recovered.',
    'promo.deleting': 'Deleting...',
    'promo.confirmDelete': 'Yes, Delete',
    'promo.discountValue': 'Discount Value',
    'promo.voucherCode': 'Voucher Code',
    'promo.quotaUsed': 'Quota Used',
    'promo.validAt': 'Valid At',
    'promo.allBranches': 'All Branches',
    'promo.specificBranch': 'Specific Branch',
    'promo.period': 'Period',
    'promo.usageLimit': 'Usage Limit',
    'promo.usageLimitDesc': 'Max {n}x transaction per user',
    'promo.exclusive': 'Exclusive',
    'promo.insights': 'Insights',
    'promo.globalAnalytics': 'Global Analytics',
    'promo.powerTip': 'Power Tip',
    'promo.powerTipDesc': 'Exclusive vouchers for loyal members can increase retention by up to 35%. Use the "Specific User" feature for more precise targeting.',
    'promo.deleteSuccess': 'Campaign deleted successfully',
    'promo.deleteFailed': 'Failed to delete campaign',

    // ── Users Page ────────────────────────────────────────────────
    'users.subtitle': 'Manage system user access, roles, and data',
    'users.registered': 'users registered',
    'users.addUser': 'Add User',
    'users.superAdmin': 'Super Admin',
    'users.branchAdmin': 'Branch Admin',
    'users.member': 'Member',
    'users.cashier': 'Cashier',
    'users.activeUsers': 'Active Users',
    'users.totalMember': 'Total Members',
    'users.activeMember': 'Active Members',
    'users.totalMemberPoints': 'Total Member Points',
    'users.serverStatus': 'Server Status',
    'users.searchPlaceholder': 'Search name or email...',
    'users.allRoles': 'All Roles',
    'users.tableUser': 'User',
    'users.tableRole': 'Role',
    'users.tableBranch': 'Branch',
    'users.tableStatus': 'Status',
    'users.tablePoints': 'Points',
    'users.tableAction': 'Action',
    'users.noMatch': 'No identities matching your filter.',
    'users.clearAllFilters': 'Clear all filters',
    'users.editIdentity': 'Edit Identity',
    'users.editDesc': 'Update profile details and access rights.',
    'users.fullName': 'Full Name',
    'users.enterFullName': 'Enter full name',
    'users.emailAddress': 'Email Address',
    'users.locationAssignment': 'Location Assignment',
    'users.selectLocation': 'Select Location',
    'users.userRole': 'User Role',
    'users.roleImmutable': '* Role type is immutable. Revoke access to change roles.',
    'users.discardChanges': 'Discard Changes',
    'users.updateIdentity': 'Update Identity',
    'users.revokeAccess': 'Revoke Access',
    'users.revokeDesc': 'Are you sure you want to revoke access for {name}? This will permanently delete their account and terminal access.',
    'users.keepUser': 'No, Keep User',
    'users.revokeNow': 'Revoke Now',
    'users.sendVoucher': 'Send Voucher',
    'users.sendVoucherDesc': 'Gift a special promo code directly to {name}.',
    'users.voucherCode': 'Voucher Code',
    'users.discountType': 'Discount Type',
    'users.discountValue': 'Discount Value',
    'users.minPurchase': 'Min. Purchase (Optional)',
    'users.syncingIdentities': 'Synchronizing Identities...',
    'users.identityCreated': 'Identity created successfully',
    'users.identityUpdated': 'Identity updated successfully',
    'users.identityRevoked': 'Identity for {name} revoked',
    'users.voucherSent': 'Voucher sent to {name}',

    // ── Create User Page ──────────────────────────────────────────
    'createUser.title': 'Create New User',
    'createUser.subtitle': 'Add a new team member to the system',
    'createUser.back': 'Back to Users',
    'createUser.fullName': 'Full Name',
    'createUser.email': 'Email',
    'createUser.role': 'Role',
    'createUser.password': 'Password',
    'createUser.branch': 'Branch',
    'createUser.creating': 'Creating...',
    'createUser.create': 'Create User',

    // ── Broadcast Page ────────────────────────────────────────────
    'broadcast.subtitle': 'Send announcements to all branches and users',
    'broadcast.subtitleDesc': 'Communication and notification center',
    'broadcast.composeMessage': 'Compose Message',
    'broadcast.targetAudience': 'Target Audience',
    'broadcast.selectAudience': 'Select Audience',
    'broadcast.allBranches': 'All Branches',
    'broadcast.specificBranch': 'Specific Branch',
    'broadcast.allMembers': 'All Members',
    'broadcast.selectBranch': 'Select Branch',
    'broadcast.targetBranch': 'Target Branch',
    'broadcast.subjectHeader': 'Subject / Header',
    'broadcast.subjectPlaceholder': 'e.g. System Maintenance Alert',
    'broadcast.messageBody': 'Message Body',
    'broadcast.messagePlaceholder': 'Describe the update in detail...',
    'broadcast.warningAllMembers': 'This message will be sent to all registered Members (Push Notifications enabled).',
    'broadcast.warningSpecificBranch': 'This message will be sent to admins at {branch}.',
    'broadcast.warningAllBranches': 'This message will be instantly delivered as a push notification to all active branch managers.',
    'broadcast.sending': 'Sending...',
    'broadcast.dispatch': 'Dispatch Broadcast',
    'broadcast.recipients': 'Recipients',
    'broadcast.target': 'Target',
    'broadcast.allMembersLabel': 'All Members',
    'broadcast.branchAdminLabel': 'Branch Admin',
    'broadcast.allBranchAdmins': 'All Branch Admins',
    'broadcast.targetScope': 'Target Scope',
    'broadcast.global': 'Global',
    'broadcast.local': 'Local',
    'broadcast.network': 'Network',
    'broadcast.integrityStatus': 'Integrity Status',
    'broadcast.active': 'Active',
    'broadcast.recentHistory': 'Recent History',
    'broadcast.noHistory': 'No broadcast history found.',
    'broadcast.loadingHub': 'Loading Communication Hub...',
    'broadcast.successSent': 'Broadcast dispatched successfully!',
    'broadcast.fillAllFields': 'Please fill in all fields',

    // ── Transactions Page ─────────────────────────────────────────
    'transactions.subtitle': 'Transaction and payment history',
    'transactions.subtitleDesc': 'Monitor all sales activity',
    'transactions.totalTransactions': 'Total Transactions',
    'transactions.totalRevenue': 'Total Revenue',
    'transactions.avgOrder': 'Avg. Order',
    'transactions.completed': 'Completed',
    'transactions.searchInvoice': 'Search invoice number...',
    'transactions.allBranches': 'All Branches',
    'transactions.searchBranch': 'Search branch...',
    'transactions.branchNotFound': 'Not found.',
    'transactions.newest': 'Newest',
    'transactions.oldest': 'Oldest',
    'transactions.highest': 'Highest',
    'transactions.lowest': 'Lowest',
    'transactions.list': 'Transaction List',
    'transactions.found': 'transactions found',
    'transactions.noTransactions': 'No transactions',
    'transactions.invoice': 'Invoice',
    'transactions.date': 'Date',
    'transactions.branch': 'Branch',
    'transactions.total': 'Total',
    'transactions.status': 'Status',
    'transactions.customer': 'Customer',
    'transactions.items': 'Items',
    'transactions.detail': 'Transaction Detail',
    'transactions.page': 'Page',
    'transactions.of': 'of',

    // ── Monitor Page ──────────────────────────────────────────────
    'monitor.subtitle': 'Monitor inventory stock across all branches',
    'monitor.subtitleDesc': 'Real-time updates from all locations',
    'monitor.searchBranch': 'Search branch...',
    'monitor.totalBranches': 'Total Branches',
    'monitor.activeLocations': 'active locations',
    'monitor.lowStockItems': 'Low Stock Items',
    'monitor.acrossNetwork': 'across network',
    'monitor.criticalAlerts': 'Critical Alerts',
    'monitor.needRestock': 'need restocking',
    'monitor.items': 'items',
    'monitor.noBranch': 'No branches found',
    'monitor.lowStock': 'Low Stock',
    'monitor.healthy': 'Healthy',
    'monitor.outOfStock': 'Out of Stock',
    'monitor.total': 'Total',
    'monitor.product': 'Product',
    'monitor.sku': 'SKU',
    'monitor.stock': 'Stock',
    'monitor.lastUpdated': 'Last Updated',

    // ── AI Insights / Analysis ────────────────────────────────────
    'ai.title': 'AI Insights',
    'ai.subtitle': 'Smart analysis powered by artificial intelligence',
    'ai.analyzing': 'Analyzing...',
    'ai.generateInsights': 'Generate Insights',
    'ai.noInsights': 'No insights yet',
    'ai.noInsightsDesc': 'Click the button above to start AI analysis',
    'ai.recommendations': 'Recommendations',
    'ai.trends': 'Trends',
    'ai.alerts': 'Alerts',

    // ── Login Page ────────────────────────────────────────────────
    'login.welcomeBack': 'Welcome Back',
    'login.subtitle': 'Please enter your credentials to manage your assigned business unit.',
    'login.username': 'Username',
    'login.usernamePlaceholder': 'Enter your username',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signIn': 'Sign In to Dashboard',
    'login.signingIn': 'Signing In...',
    'login.tagline': 'Unified Business Intelligence.',
    'login.taglineDesc': 'Take full control of your enterprise operations with centralized data monitoring and real-time inventory synchronization.',

    // ── Branch Selector / Context ─────────────────────────────────
    'branch.consolidated': 'CONSOLIDATED',
    'branch.yourBranch': 'YOUR BRANCH',
    'branch.selectUnit': 'Select Operation Unit',

    // ── Export Modal ──────────────────────────────────────────────
    'export.title': 'Export Report - {branch}',
    'export.desc': 'Prepare a consolidated PDF report for the current view. This will include sales velocity, revenue metrics, and branch health status for high-level operational review.',
    'export.confirm': 'Confirm & Print',
    'export.processing': 'Processing...',

    // ── Adjust Stock Modal ────────────────────────────────────────
    'adjustStock.title': 'Adjust Stock',
    'adjustStock.subtitle': 'Updating inventory for {name}. Current stock: {stock}.',
    'adjustStock.movementType': 'Movement Type',
    'adjustStock.selectType': 'Select type',
    'adjustStock.restock': 'Restock (+)',
    'adjustStock.sale': 'Manual Sale (-)',
    'adjustStock.damage': 'Damage/Loss (-)',
    'adjustStock.adjustment': 'Absolute Adjust (=)',
    'adjustStock.quantity': 'Quantity',
    'adjustStock.reason': 'Reason / Notes (Optional)',
    'adjustStock.reasonPlaceholder': 'e.g. Delivered by supplier ABC',
    'adjustStock.confirmUpdate': 'Confirm Update',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('app_language');
      return (saved === 'id' || saved === 'en') ? saved : 'id';
    } catch {
      return 'id';
    }
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('app_language', lang);
    } catch {
      // ignore
    }
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}
